function signQ(sign, a, b, c, d) {
  return { text: 'What does it say? Choose the correct explanation.', sign, options: { A: a, B: b, C: c, D: d } };
}

export const PART2_3_20 = {
  3: {
    11: signQ(`FOR SALE\nGremlins Computer Games (age 8 and above)\nUnwanted gift – box unopened\nRing 282137`, `The owner of the computer games that is for sale has never used it.`, `The computer games is for sale because the owner is too old for it.`, `The person selling the computer games no longer wants to play with it.`, `The seller can't use it.`),
    12: signQ(`STUDENTS WITHOUT MEAL TICKETS FOR TODAY MUST PAY FOR ALL FOOD, SNACKS AND DRINKS`, `You have to pay for meal if you don't have a ticket.`, `You cannot use ticket to pay for your meal today.`, `If you need a meal ticket you can pay for it here.`, `Unless you need a meal ticket, you can pay for it here.`),
    13: signQ(`Sorry\nNo dogs Unless Carried`, `Dogs must walk with their owners.`, `Dogs must be kept on a chain.`, `Dogs must be held.`, `Dogs must be free.`),
    14: signQ(`Important!\nDo NOT connect the printer cable to your computer until you have installed the software provided.`, `You must connect the cable after you install the software.`, `You must connect the cable before you install the software.`, `You must not connect the cable to the printer.`, `You must connect the cable right now.`),
    15: signQ(`SUPERSAVER TICKETS CANNOT BE USED ON FRIDAYS`, `You need a special ticket to travel on a Friday.`, `You can save money by travelling on a Friday.`, `Supersaver tickets can be used every day except Fridays.`, `You should save money for travelling.`)
  },
  4: {
    11: signQ(`Maria,\nMum wanted me to go shopping after school and get vegetables for tonight's supper. She forgot I'm going swimming - could you do it instead? Let me know!\nSean`, `Sean is hoping that Maria will do him a favor.`, `Maria has to prepare supper after school tonight.`, `Mum has asked Sean to help her instead of going swimming.`, `Maria has to go swimming after school.`),
    12: signQ(`From: Martin    To: Ben\nI'm thinking about what subjects to study at college. Computer Science looks interesting, but I don't know much about it. I'd really like your opinion!`, `Martin is emailing Ben to ask for advice about a college course.`, `tell Ben his decision about a subject.`, `make a suggestion to Ben about studying.`, `tell Ben to give his opinion.`),
    13: signQ(`ABC CINEMA\nALL THIS WEEK – Startruck\nSaturday/Sunday: student reductions (ID card required)`, `There is a special showing of Startruck for students on Saturday and Sunday.`, `To see Startruck more cheaply, go at the weekend with your student card.`, `It's possible for students to see Startruck at reduced price all this week.`, `There is a film show every night.`),
    14: signQ(`To: All students\nFrom: Mrs. Anderson\nSchool concert practice: all actors taking part should attend, and also musicians – we're short of those! Art students – thanks for painting the stage!`, `For the concert, Mrs. Anderson needs more students who know how to act.`, `are willing help with the stage.`, `can play a musical instrument.`, `can play sports.`),
    15: signQ(`Andrew,\nMy dad's not taking me to the volleyball match tonight – I'm sick so we can't give you a lift as promised. Would your dad drive you instead?\nCall me,\nMax`, `Max wants to know if Andrew's dad can drive them both to the match.`, `Andrew is asking whether he can have a lift to the match with Max.`, `Max is suggesting Andrew's dad may have to take Andrew to the match.`, `Max wants Andrew to collect him.`)
  },
  5: {
    11: signQ(`From: Sarah Lewis\nTo: Ellie Simpson\nHi Ellie,\nJust to let you know that Martin is ill, so he isn't coming bowling with us. Paul still wants to come, but he has to be home at eight o'clock.\nIs it ok to meet at five o'clock instead of six so that we have enough time?\nSarah`, `if Ellie can meet up earlier than planned.`, `if Paul wants to go bowling with them.`, `if eight o'clock is too late to get home.`, `if we have enough time.`),
    12: signQ(`SPORTS HALL\nFinal five minutes of bookings must be used to put equipment away`, `Bookings now include an extra five minutes for equipment to be put away.`, `You have five minutes after bookings have finished to return any sports etc.`, `The hall must be cleared of equipment in the five minutes before bookings end.`, `The hall must be closed in the five minutes before bookings end.`),
    13: signQ(`BOAT RACE!\nSaturday from 3 pm at Green Park Lake.\nAll teams should sign up before Thursday to take part.\nBig prizes for the winners`, `Arrive at the lake on time.`, `Register before the race.`, `Meet at the park on Thursday.`, `Meet at the Green Lake on Friday.`),
    14: signQ(`All passengers please note:\nRemember to put your ticket in the machine at the platform gate.`, `at an airport`, `at a railway station.`, `on a bus.`, `at a restaurant.`),
    15: signQ(`FOR SALE\nAlmost new smartphone still in its box.\nLots of games and other applications on already.\nCall 937764410`, `you can do many things with this phone.`, `the phone is new.`, `someone wants to buy a smartphone.`, `you have to pay a lot of money to buy the phone.`)
  },
  6: {
    11: signQ(`Food served daily\n9.00 A.m.-5.00 p.m\nLunchtime\nSpecial offer\n50% off all meals for the over-60s`, `Meals are half price between the hours of nine and five.`, `There is special food for people who are 60 years old.`, `There is lunchtime discount for people over the age of 60.`, `The food is served five days a week.`),
    12: signQ(`From: College office\nTo: All students\nPlease note that student identity cards will be available for collection from 25 September.`, `Students should bring their identity cards with them on 25 September.`, `Student identity cards are only available until 25 September.`, `The first day students can pick up identity cards is 25 September.`, `The students go to the college office every day.`),
    13: signQ(`This car park has\n24-hour security\ncameras in operation`, `The cameras are not operating at the moment.`, `There is security in this car park day and night.`, `This car park is only safe during the day.`, `This car park is not safe during the night.`),
    14: signQ(`Please keep your receipt\nRefund or exchange available up to 20 days after you buy clothes.\nShow your receipt when returning any items`, `You must wait for twenty days before you bring anything back here.`, `Everyone can get their money back for clothes they bought here.`, `If you want to take something back, you must prove when you bought it.`, `You don't need to keep the receipt after buying goods here.`),
    15: signQ(`Great sports bike\nIn perfect condition - less than two years old - quick sale needed - offers welcome (not less than €100). Abdul 0775 221 321`, `Abdul's bike needs only a few repairs.`, `Abdul bought this bike two years ago.`, `Abdul would accept €100.`, `Abdul needs to sell a motorbike.`)
  },
  7: {
    11: signQ(`Hot and cold\nsnacks served\nAll day`, `You can buy drinks here, but not food.`, `You can get a light meal here.`, `Sit down and the waiter come to serve you.`, `We sell food in the morning.`),
    12: signQ(`From: Tina\nTo: Yolanda\nDid I leave a book in your car? The thing is, it's not mine - I borrowed it from my brother who now wants it back!`, `return the book she borrowed.`, `lend her a book.`, `look for a book she has lost.`, `buy a new book.`),
    13: signQ(`ALL VISITORS SHOULD\nREPORT TO THE OFFICE\nON ARRIVAL`, `Please go to the office before you leave.`, `Please call the office to make an appointment.`, `Please go the office when you first come here.`, `Please call the office after you leave.`),
    14: signQ(`To: Luca\nFrom: Matteo\nThe football match is going to be on Saturday this week, instead of Sunday. Usual time and place. Everyone else can still play. OK for you?`, `will take place on a different day.`, `will have different players.`, `will be starting later than usual.`, `will be cancelled.`),
    15: signQ(`PLEASE SPEAK QUIETLY\nIN THE LIBRARY AREA. PEOPLE ARE STUDYING NEARBY`, `You can only stay here if you are studying.`, `You should try not to disturb people.`, `You are not allowed to talk here.`, `You are not allowed to study here.`)
  },
  8: {
    11: signQ(`To: Emily\nFrom: Katie\nIf you bring your student card tomorrow, your train ticket will cost less. I've found my card. See you in queue at ticket office.`, `Katie will meet Emily before they get on the train.`, `Emily's train ticket will be cheaper than Katie's.`, `Katie will buy Emily's train ticket for her.`, `Katie hasn't found her student card.`),
    12: signQ(`Good sports bike\nIn perfect condition - less than two years old - quick sale needed - offers welcome (not less than €150).\nTim 0775 221 321`, `Tim's bike needs only a few repairs.`, `Tim bought this bike two years ago.`, `Tim would accept €150.`, `Tim wants to sell his motorbike.`),
    13: signQ(`LOCKERS IN THIS AREA\nARE RESERVED FOR USE\nBY VISITING TEAM ONLY`, `Anyone who takes part in a swimming competition may use these lockers.`, `Swimmers from visiting team needn't pay to use lockers.`, `Members of the local swimming team can't use these lockers.`, `Members of visiting team can't use these lockers.`),
    14: signQ(`EXIT\nTHIS DOOR MAY ONLY BE USED BY STAFF AFTER 5 P.M`, `You must ask a member of staff to unlock this door.`, `People who work here must leave the building by 5 p.m.`, `You may use this door in the evening if you work here.`, `You can't work here after 5p.m.`),
    15: signQ(`Chris\nI've written this letter to Sam, but I can't find his address. Have you got it? If not, can you ring Mum and ask her? Then please post it.\nSarah`, `Chris should phone Sam if he doesn't know the address.`, `send the letter when she has found out the address.`, `ask Mum to write the address and then send the letter.`, `find Sam's address and write a letter to him.`)
  },
  9: {
    11: signQ(`TENNIS LESSONS\nIn bad weather, table tennis will take place in the clubhouse instead.`, `Tennis lessons may take place indoors or outdoors, depending on the weather.`, `The next tennis lesson has been cancelled due to bad weather.`, `If it rains, a different activity will be available.`, `If it rains, a different activity will not be available.`),
    12: signQ(`ZIGGY'S\nINTERNET café\n45 mins - $1.00\n4 hours or more - $5.00`, `You can use the internet for up to four hours at a time`, `If you wish to use the internet for more than 45 minutes speak to Ziggy.`, `There is a maximum charge of $5.00 to use the Internet.`, `There is a minimum charge of $5.00 to use the internet.`),
    13: signQ(`James - I loved that T-shirt you were wearing last night! Did you get it from a shop in town? I'd really like a similar one for myself. - Tamara`, `when James will wear his new T-shirt.`, `when James bought his T-shirt.`, `which T-shirt James bought yesterday.`, `where James bought his T-shirt.`),
    14: signQ(`Hi Kath,\nI climbed this mountain yesterday. It was hard work but the clouds lifted when I got to the top so it was worth it in the end!\nHelen`, `Helen enjoyed climbing the mountain but couldn't see anything from the top.`, `Helen regrets her decision to climb the mountain.`, `Helen didn't climb this mountain yesterday.`, `Although it was difficult, Helen was pleased she had climbed the mountain.`),
    15: signQ(`From: Simon\nTo: Tim\nI'm going camping with Eddie next weekend. Do you want to join us? If you do, we'll need to use your big tent. Call me this evening.`, `to ask Tim to lend him a tent.`, `to tell Tim about a change of plan.`, `to invite Tim on a camping trip.`, `to ask Tim to lend him a money.`)
  },
  10: {
    11: signQ(`From tomorrow, buses will depart every 10 minutes instead of every 20 minutes.`, `Buses will leave ten minutes earlier tomorrow.`, `Until tomorrow, bus journeys will take ten minutes longer.`, `After today, there will be more buses than before.`, `After today, there will be fewer buses than before.`),
    12: signQ(`Sports Hall\nDon't leave clothes in lockers overnight. Keys for lockers available at reception desk`, `You must remove your clothes from the lockers by the end of the day.`, `You mustn't leave keys in the lockers after taking your clothes out.`, `Any clothes left overnight can be collected from the reception desk.`, `You mustn't remove your clothes from the lockers by the end of the day.`),
    13: signQ(`To John\nFrom Saskia\nAnna's going to book the hotel tonight for our holiday. She wants you to send her £50 as she has to pay a deposit. Ring her if that's a problem.`, `let Anna know if he isn't able to give her £50.`, `tell Anna if he doesn't want to go to the hotel.`, `send the deposit to the hotel for Anna.`, `let Anna know if he is able to give her £50.`),
    14: signQ(`Go to desk in corner for concert tickets already paid for. Do not queue here.`, `There are still some tickets available at the desk in the corner.`, `You shouldn't queue here if you've paid for your ticket in advance.`, `You should go to the desk in the corner to pay for your ticket.`, `You should queue here if you've paid for your ticket in advance.`),
    15: signQ(`Gianni,\nA friend of mine has lent me this book about Peru. I know you're flying next week so why don't you read it first?\nSarah`, `Sarah is suggesting that Gianni reads the book before she does.`, `Sarah's friend recommended that Gianni read the book before his trip.`, `Sarah has read the book and is advising Gianni to read it.`, `Sarah's friend recommended that Gianni read the book after his trip.`)
  },
  11: {
    11: signQ(`From tomorrow, trains will depart every 15 minutes instead of every 20 minutes.`, `Until tomorrow, train journeys will take ten minutes longer.`, `Trains will leave ten minutes earlier tomorrow.`, `After today, there will be more trains than before.`, `After today, there will be fewer trains than before.`),
    12: signQ(`Sports Hall\nDon't leave bags in lockers overnight. Keys for lockers available at reception desk.`, `You must remove your bags from the lockers by the end of the day.`, `You mustn't leave keys in the lockers after taking your clothes out.`, `Any clothes left overnight can be collected from the reception desk`, `You mustn't remove your clothes from the lockers by the end of the day.`),
    13: signQ(`To Mary\nFrom Linda\nTina's going to book the hotel tonight for our holiday. She wants you to send her £60 as she has to pay a deposit. Ring her if that's a problem.`, `tell Tina if he doesn't want to go to the hotel.`, `let Anna know if he isn't able to give her £60.`, `send the deposit to the hotel for Tina`, `let Tina know if he is able to give her £50`),
    14: signQ(`Go to table in corner for concert tickets already paid for. Do not queue here.`, `There are still some tickets available at the desk in the corner.`, `You should go to the table in the corner to pay for your ticket.`, `You should queue here if you've paid for your ticket in advance.`, `You shouldn't queue here if you've paid for your ticket in advance.`),
    15: signQ(`Mary,\nA friend of mine has lent me this book about Peru. I know you're flying next week so why don't you read it first?\nLinda`, `Linda has read the book and is advising Mary to read it.`, `Linda is suggesting that Mary reads the book before she does.`, `Linda's friend recommended that Mary read the book before his trip.`, `Linda's friend recommended that Mary read the book after his trip.`)
  },
  12: {
    11: signQ(`PLEASE SPEAK QUIETLY\nIN THE LIBRARY AREA.\nPEOPLE ARE STUDYING NEARBY`, `You can only stay here if you are studying.`, `You should try not to disturb people.`, `You are not allowed to talk here.`, `You are not allowed to drink here.`),
    12: signQ(`From: Linda\nTo: Tina\nDid I leave a dictionary in your car? The thing is, it's not mine - I borrowed it from my brother who now wants it back!`, `lend her a dictionary`, `buy her a dictionary`, `return the dictionary she borrowed.`, `look for a dictionary she has lost.`),
    13: signQ(`ALL GUESTS SHOULD\nREPORT TO THE OFFICE\nON ARRIVAL`, `Please go the office when you first come here.`, `Please go to the hotel before you leave.`, `Please call the hotel to make an appointment`, `Please go the police station when you come here.`),
    14: signQ(`Telephone message\nTo: Tim\nFrom: Matteo\nThe soccer match is going to be on Saturday this week, instead of Sunday. Usual time and place. Everyone else can still play. OK for you?`, `will have different players.`, `will take place on a different day`, `will be starting later than usual.`, `will take place on Monday.`),
    15: signQ(`Linda,\nMum wanted me to go shopping after school and get fruits for tonight's supper. She forgot I'm going fishing - could you do it for me? Let me know!\nSean`, `Linda has to prepare supper after school tonight.`, `Mum has asked Sean to help her instead of going fishing.`, `Sean is hoping that Linda will do him a favour.`, `Linda has to go swimming after school.`)
  },
  13: {
    11: signQ(`Please use upstairs waiting room if you have an appointment with the doctor`, `wait upstairs to see the doctor.`, `You go upstairs to make appointments with the doctor.`, `The doctor can only see patients with appointments.`, `use the lift instead of stairs to see the doctor.`),
    12: signQ(`Teenager's Exhibition\nMachines have buttons which should be pressed to make them start.`, `Children should be careful not to touch the machines.`, `The machines are designed so that teenagers can operate them.`, `The machines are models which do not work.`, `Machines are broken and use buttons to start.`),
    13: signQ(`SPORTS CENTER\nPLEASE REPORT LOST PROPERTY IMMEDIATELY TO ANY STAFF`, `ask a member of staff to show you the lost property list.`, `tell the staff what you have lost without delay.`, `The staff will fill in a lost property report immediately.`, `tell any staff member about found property.`),
    14: signQ(`Boat trip:\nIf you've paid a deposit, final payment due tomorrow`, `paying what you owe for the boat trip.`, `saying you want to go on the boat trip.`, `paying a deposit for the boat trip.`, `booking a place for the trip`),
    15: signQ(`Mary,\nTom's decided to attend the advanced violin class and not the intermediate, and hopes you will too. Please let him know. It starts immediately after the immediate class.\nLee`, `Mary should tell Tom the exact time his violin class starts.`, `Tom is asking to join the advanced violin class.`, `Tom wants Mary to go to the same violin class as him.`, `Tom invites Mary to attend the intermediate class.`)
  },
  14: {
    11: signQ(`NO BIKE AGAINST THE DOOR PLEASE!`, `do not leave your bike touching the door.`, `Broken glass may damage your bike tires.`, `Your bike may not be safe here.`, `lean your bike on glass`),
    12: signQ(`NOTICES\nTo order your class photo, sign below.\n$8.50 each, 20% discount on three or more copies (payment to office immediately)`, `There will be a class photo if enough people sign here.`, `Your photo will cost less if you pay the office in advance`, `The price per photo is reduced if several are ordered at once.`, `Your photo will cost more if you pay the office in advance`),
    13: signQ(`Company security\nOffice staff must have their identity cards with them at all time`, `show your identity cards when asked to do so.`, `The company insists office workers carry an identity card.`, `Staff identity cards are available at the office.`, `It is not required to carry ID cards.`),
    14: signQ(`Evening performance\nREFRESHMENTS ARE SERVED ONLY DURING THE INTERVAL`, `Help yourself to drinks after the performance`, `Snacks are available before the performance.`, `You can have a drink during the break.`, `You can refresh yourself.`),
    15: signQ(`Tim,\nNo more eggs left, so I'll collect some at the farm. Please buy the bread in town and tell Megan to get a salad ready tonight.\nMum`, `salad.`, `bread.`, `eggs.`, `butter`)
  },
  15: {
    11: signQ(`Shop delivery vehicles unload here 09.00 a.m. - 11.00 a.m. daily.\nCustomer parking permitted at any other time`, `customers may not park outside the shop for up to two hours.`, `You may unload your delivery vehicle there after ten o'clock.`, `Customers can park here from 08.00 a.m. to 10.00 a.m.`, `Customers may park here when vehicles are not unloading.`),
    12: signQ(`TONIGHT'S PERFORMANCE\nThis window is only for collecting the tickets you have paid for`, `Remaining tickets for tonight's performance are on sale at that window.`, `This window is only for collecting the tickets you have reserved.`, `There are no more tickets available for tonight's performances.`, `You can get tickets from this window only.`),
    13: signQ(`Debie,\nBrian's decided to attend the advanced guitar class and not the intermediate, and hopes you will too. Please let him know. It starts immediately after the immediate class.\nVicky`, `Debie shouldn't tell Brian the exact time his guitar class starts.`, `Brian wants Debie to go to the same guitar class as him.`, `Brian is asking to join the advanced guitar class that Debie teaches.`, `Brian advises Debie to go to the intermediate class.`),
    14: signQ(`A NARROW TUNNEL\nCyclists – leave road and join pavement, but look out for pedestrians!`, `Car drivers should not look out for cyclists and pedestrians in the road.`, `This tunnel is for cyclists and pedestrians only.`, `Pedestrians and cyclists should go through the tunnel on the pavement.`, `Cyclists can join the pavement without noticing the pedestrians.`),
    15: signQ(`Lifts out of order\nuntil further notice\nAccess to chemistry labs by the stairs.`, `You have to walk up to the labs because the lift is not working.`, `There will soon be a new lift to the upstairs labs.`, `Students and staff cannot get to the science labs at the moment.`, `You can contact chemistry labs by lift or by the stairs.`)
  },
  16: {
    11: signQ(`SPORTS CENTER\nPLEASE REPORT LOST PROPERTY IMMEDIATELY TO ANY MEMBER OF STAFF`, `Ask a member of staff to show you the lost property list.`, `Tell the staff what you have lost without delay.`, `The staff will fill in a lost property report immediately.`, `Tell the sports center found property.`),
    12: signQ(`From: John\nTo: Nell\nCan you call the cinema from home and check film time before leaving? Let me know what time we should get there.`, `contact John after phoning the cinema.`, `ring John after arriving at the cinema.`, `go to the cinema to check when the film start.`, `leave home before checking the time.`),
    13: signQ(`Parents are reminded that\nThis is not a playground-\nPLEASE KEEP CHILDREN OFF SCULPTURES!`, `Families can only watch sports events in this park.`, `Children mustn't climb on the sculptures.`, `Some of the sculptures are unsuitable for children.`, `Parents can allow children to play in the playground.`),
    14: signQ(`Hi everyone! When exams are over, what about trying to the new club in green street?\nI haven't been there yet.\nMack`, `Mack recommends a new club to his friends.`, `Mack want to go clubbing before the exams.`, `Mack suggests going to a club after the exams.`, `Mack wants to go over the exam.`),
    15: signQ(`Choose a pair of gloves\nFree\nWHEN YOU BUY A COAT TODAY`, `You are given some gloves if you buy a coat today.`, `You can get a discount on a coat if you buy some gloves today.`, `We have gloves to match the coats we sell.`, `Coat are free today if you buy gloves.`)
  },
  17: {
    11: signQ(`[Bicycle repair shop notice]`, `Polly can leave her bicycle for repair even when the shop is closed.`, `Polly should leave her keys so that the repair shop can lock her bicycle.`, `Polly's bicycle will be left outside when it is repaired.`, `Polly can't leave her bicycle for repair even when the shop is closed.`),
    12: signQ(`Choose a pair of gloves\nFree\nWHEN YOU BUY A COAT TODAY`, `You can get a discount on a coat if you buy some gloves today.`, `You are given some gloves if you buy a coat today.`, `We have gloves to match the coats we sell.`, `You can get two pairs of gloves if you try on a coat today.`),
    13: signQ(`LOST PROPERTY\nItems not collected within two weeks will be disposed of`, `We give lost property away if it is not collected after two weeks.`, `We will look after your property for two weeks if you pay a fee.`, `We keep things people have lost for a maximum of two weeks.`, `We will sell lost property immediately it is left.`),
    14: signQ(`Clive,\nMy brother will return your Walkman when he gets back from his trip.\nMark`, `Clive borrowed Mark's Walkman.`, `Clive's brother will return the Walkman to Mark.`, `Mark wants to use Clive's Walkman on a journey.`, `Mark hope to keep Clive's Walkman in his car.`),
    15: signQ(`PHOTOCOPIER\nPlease pay for copies at reception when you have finished`, `Do your photocopying and pay for it when you leave.`, `Put your money in the photocopier before you start to use it.`, `Tell an assistant how many photocopies you need.`, `Count number of copies and pay for it if you have money.`)
  },
  18: {
    11: signQ(`Please use upstairs waiting room if you have an appointment with the nurse`, `You can go upstairs to make appointments with the nurse.`, `The nurse can only see patients with appointments.`, `Wait upstairs to see the nurse.`, `The nurse may wait you in the waiting room.`),
    12: signQ(`Children's Science Exhibition\nMachines have buttons which should be pressed to make them start.`, `The machines are designed so that children can operate them.`, `Children should be careful not to touch the machines.`, `The machines are models which do not work.`, `Children are not allowed to start the machines.`),
    13: signQ(`SPORTS CENTER\nPLEASE REPORT LOST PROPERTY IMMEDIATELY TO ANY MEMBER OF STAFF`, `Ask a member of staff to show you the lost property list.`, `Tell the staff what you have lost without delay.`, `The staff will fill in a lost property report immediately.`, `Phone any member of staff if you want to take lost property.`),
    14: signQ(`Coach trip:\nNo places available. If you've paid a deposit, final payment due tomorrow`, `paying what you owe for the coach trip.`, `saying you want to go on the coach trip.`, `paying a deposit for the coach trip.`, `saying you don't have any places to go on a coach trip.`),
    15: signQ(`Debbies,\nBrian's decided to attend the advanced guitar class and not the intermediate, and hopes you will too. Please let him know. It starts immediately after the immediate class.\nVickie`, `Debbie should tell Brian the exact time his guitar class starts.`, `Brian wants Debbie to go to the same guitar class as him.`, `Brian is asking to join the advanced guitar class.`, `Brian wants his friend Debbie to go to the immediately guitar class.`)
  },
  19: {
    11: signQ(`Shop delivery vehicles unload here 08.00 a.m. - 10.00 a.m. daily.\nCustomer parking permitted at any other time`, `Customers may park here when vehicles are not unloading.`, `customers may park outside the shop for up to two hours.`, `You may unload your delivery vehicle here after ten o'clock.`, `Customers can park here from 08.00 a.m. to 10.00 a.m.`),
    12: signQ(`TONIGHT'S PERFORMANCE\nThis window is only for collecting tickets you have paid for.`, `This window is only for collecting tickets you have reserved.`, `Remaining tickets for tonight's performance are on sale at this window.`, `There are no more tickets available for tonight's performance.`, `You can get tickets from this window only.`),
    13: signQ(`Debbie,\nBrian's decided to attend the advanced guitar class and not the intermediate, and hopes you will too. Please let him know. It starts immediately after the immediate class.\nVickie`, `Brian wants Debbie to go to the same guitar class as him.`, `Debbie should tell Brian the exact time his guitar class starts.`, `Brian is asking to join the advanced guitar class that Debbie teaches.`, `Brian advises Debbie to go to the intermediate class.`),
    14: signQ(`NARROW TUNNEL\nCyclists – leave road and join pavement, but look out for pedestrians!`, `This tunnel is for cyclists and pedestrians only.`, `Car drivers should look out for cyclists and pedestrians in the road.`, `Pedestrians and cyclists should go through the tunnel on the pavement.`, `Cyclists can join the pavement without noticing the pedestrians.`),
    15: signQ(`KEEP OFF THE GRASS!\nPlease walk on the path around the park and keep dogs on leads.\nThank you.`, `Dogs aren't allowed in the park`, `There are lots of paths in the park.`, `Visitors to the park shouldn't walk on the grass.`, `Keeping dogs on leads is permitted.`)
  },
  20: {
    11: signQ(`£5 extra charge if hired cycles and helmets are not returned by 6 pm.`, `If you bring a bike back later than 6 pm, you will pay more.`, `Hire of a bicycle and helmet cost £5 if you return them before 6 pm.`, `Cyclists must wear helmets and be back no later than 6 pm.`, `You needn't return with helmets at 6 pm.`),
    12: signQ(`From: Sarah Lewis\nTo: Ellie Simpson\nHi Ellie,\nJust to let you know that Martin is ill, so he isn't coming bowling with us. Paul still wants to come, but he has to be home at eight o'clock.\nIs it ok to meet at five o'clock instead of six so that we have enough time?\nSarah`, `if Ellie can meet up earlier than planned.`, `if Paul wants to go bowling with them.`, `if eight o'clock is too late to get home.`, `if Ellie wants to meet at home.`),
    13: signQ(`Hollins Farm Campsite\nNo groups of 4 or more unless by previous arrangement.`, `All campers must reserve a place in advance.`, `Groups bigger than four are not allowed on this site.`, `Groups of more than three should contact the campsite before arriving.`, `Four or more groups can camp here.`),
    14: signQ(`Lift out of order\nuntil further notice\nAccess to chemistry labs by the stairs.`, `There will soon be a new lift to the upstairs labs.`, `Students and staff cannot get to the science labs at the moment.`, `You have to walk up to the labs because the lift is not working.`, `You can contact chemistry labs by lift or by the stairs.`),
    15: signQ(`FOR SALE\nAlmost new smartphone still in its box.\nLots of games and other applications on already.\nCall 937764410`, `you can do many things with this phone.`, `the phone is new.`, `someone wants to buy a smart phone.`, `You can play fun games on the smart phone.`)
  }
};
